apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: ksqldb-server
  name: ksqldb-server
  namespace: user-gang
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ksqldb-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: ksqldb-server
    spec:
      containers:
        - env:
            - name: KSQL_BOOTSTRAP_SERVERS
              value: kafka.demo-internal:9092
            - name: KSQL_KSQL_SERVICE_ID
              value: ksql_service_
            - name: KSQL_LISTENERS
              value: http://0.0.0.0:8088/
          image: confluentinc/ksqldb-server:0.24.0
          name: ksqldb-server
          ports:
            - containerPort: 8088
          resources:
            requests:
              memory: "16Gi"
              cpu: 2
            limits:
              memory: "16Gi"
              cpu: 2
      restartPolicy: Always
status: {}
